<!DOCTYPE html>
<html lang="en-us">
    <head>
		
		
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">

		<title>Final Election Forecast &middot; Gov 1347 - 2022 Midterm Elections Blog</title>

		
		<link rel="stylesheet" href="/css/style.css">
		<link rel="stylesheet" href="/css/fonts.css">
		
		<link rel="icon" href="/favicon.ico"/>
		<link rel="icon" type="image/png" sizes="32x32" href="/images/favicon-32x32.png">
		<link rel="icon" type="image/png" sizes="16x16" href="/images/favicon-16x16.png">
		<link rel="apple-touch-icon" sizes="180x180" href="/images/apple-touch-icon.png">

		
		<link href="" rel="alternate" type="application/rss+xml" title="Gov 1347 - 2022 Midterm Elections Blog" />

		<script src="/js/darkmode.js"></script>
	</head>

    <body>
        		<nav class="nav">
			<div class="nav-container">
				<a href="/">
					
						<h2 class="nav-title">Gov 1347 - 2022 Midterm Elections Blog</h2>
					
				</a>
				<ul>
    
    
</ul>
			</div>
		</nav>

        <div id="darkModeToggle" onclick="toggleDarkMode()">
  &#9680; 
</div>

        

<main>
	


        <div class="post">
		<div class="post-info">
    <span>Written by</span>
        Jen Hughes
        <br>
        <span>on&nbsp;</span><time datetime="2022-11-05 00:00:00 &#43;0000 UTC">November 5, 2022</time>
</div>

		<h1 class="post-title">Final Election Forecast</h1>
<div class="post-line"></div>

		

		


<p>#Overview</p>
<p>Hi All! After several weeks of experimenting reworking and shifting the election is upon us meaning this is my final prediction. In the end, I have focused on a national vote share model and a resulting seat share model based on this prediction. My final prediction outlined in more detail below, predicts that Republicans will win 226 seats while Democrats will win 209. While I feel confident that the predicted seat distribution is in the right range, I was unable to fully solve issues of data limitations that we have been facing all semester which means that the confidence interval on this prediction is very large,
with over a 10 seat swing in either direction predicted as possible.</p>
<p>#The Final Model</p>
<p>My final model incorporates percent change in real disposable income from Q7 - Q8, avg expert rating, and generic ballot averages after August. While creating the model, I attempted to account for many other variables including, district level polls, party of the president, and house incumbency. However, I found that all of these variables either lowed the R-sq value of my model or introduced glaring data gaps that made modeling with any level of certainty impossible. I was also compelled by several readings across the course, particularly the collection of articles from Campbell 2018, that simpler models can still be powerful predictors.</p>
<p>#Formula</p>
<p>The final model formula I utilized is:</p>
<p>Y = 33.910 -0.554* X1 + 0.604* X2 -2.874* X3</p>
<p>whereas,</p>
<ul>
<li><p>Y = Democratic party popular vote share of two major parties (%)</p></li>
<li><p>X1 = The percent change in real disposable income between quarters 7 and 8 of a given election year</p></li>
<li><p>X2 = Support for Democrats based on an average of generic ballot polling (%)</p></li>
<li><p>X3 = The average expert rating for a given district in a given year (1-7)</p></li>
</ul>
<p>**see below for more information on the expert rating calculation</p>
<p>#Justification</p>
<p>I chose to include change in RDI from Q7 to Q8 because we’ve seen that at least in presidential elections, this metric has proven to be a good predictor of vote share (Healy and Lenz, 2014). While the impact of this metric in Congressional elections is less conclusive, it is nevertheless of the few metrics where we have comprehensive, reliable data (Enos, Gov1347). Furthermore, voters continually cite the economy as the single most important issue from election cycle to election cycle, particularly in 2022 (Pew 2022). Therefore I felt that it was important to include an explicit measure of the economy beyond just what is baked into expert predictions.</p>
<p>The next variable I included was generic ballot polling data. Using the list of generic ballot polls provided to the class, I created an average support variable for each party which took the average of every poll after August. As we’ve seen in the 2022 election cycle, themics of generic ballot polls often change after the summer months as average voters begin to pay attention to politics (FiveThirtyEight). This often takes the form of tightening polls in the fall. For this reason I decided to include polls from Sep-Nov because they more accurately represent the true stances of the electorate.</p>
<p>Finally, I included average expert rating in the model. I converted expert ratings from Cook, Rothenberg, Sabato’s Crystal Ball, and Real Clear Politics onto a 1-7 scale where 1 is a safe D seat and 7 is a safe R seat. The model treats one year-state-district as the unit of observation so our data is limited by the availability of expert ratings since the data set available to us includes only competitive races. However, looking at only competitive races may actually improve our model since there’s some reason to believe that competitive races differ from safe seats. Given the partisan makeup of the nation, a national prediction should more closely model a competitve election that a safe election.</p>
<p>While trying out different models I initially built a model using data from all election years in an attempt to preserve as much data as possible given the limited data available about house races. This gave me a prediction with an similar r-squared (0.75) but a very large prediction interval. To see if I could reduce that interval, I subset the data for just midterm years. As seen below, this model kept a similar r-squared value (0.75) but reduced the prediction interval to ~10 pts. This is still a large window but it is a much better prediction than the model where all years were included.</p>
<p>#Midterm years only model</p>
<pre><code>## 
## ===============================================
##                         Dependent variable:    
##                     ---------------------------
##                        DemVotesMajorPercent    
## -----------------------------------------------
## DSPIC_change_pct              -0.554           
##                               (0.522)          
##                                                
## D_avg_support                0.604***          
##                               (0.066)          
##                                                
## avg_rating                   -2.874***         
##                               (0.093)          
##                                                
## Constant                     33.910***         
##                               (3.129)          
##                                                
## -----------------------------------------------
## Observations                    329            
## R2                             0.757           
## Adjusted R2                    0.755           
## Residual Std. Error      2.707 (df = 325)      
## F Statistic          337.804*** (df = 3; 325)  
## ===============================================
## Note:               *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
<p>The coefficient for the change in RDI variable is -0.554. This means that a one point increase in RDI change from Q7 to Q8 is associated with a 0.554 decrease in vote share. This seems counter intuitive because we would expect that a larger increase in RDI should be positively correlated with vote share. However, this is also the only variable that is not showing as significant so it may just be that change in RDI is not a great predictor of midterm outcomes.</p>
<p>The coefficient for generic ballot supper is 0.604. This means that a one point increase in generic ballot support for Democrats translates into a 0.6 point increase in Democratic vote share. This relationship does fit what we would expect but it’s interesting that it is not a 1-to-1 relationship. The coefficient is another reminder that generic ballot polling alone does not perfectly translate into votes, demonstrating the persistent issues and uncertainty of polling.</p>
<p>The final coefficient for average expert rating shows that a 1 unit change in expert rating (from likely Dem to leans Dem for instance) is associated with a 2.9 point drop in democratic vote share. This makes sense because as a race becomes more favorable to Republicans we would expect the Democratic vote share to decrease. This is also the largest coefficient, demonstrating the reliance of the model on expert ratings which are significant.</p>
<p>Prediction:</p>
<pre><code>##       fit      lwr      upr
## 1 49.5433 44.00125 55.08535</code></pre>
<p>To make a prediction for the 2022 midterm elections based on this model, I plugged in the current data on RDI change over the last quarter, current democratic generic ballot averages, and average expert rating across all districts. This value was calculated using the expert predictions 2022 scrape provided to the course. This aggregates district ratings for all districts from predictions by Cook, Rothenberg, Sabatos Crystal Ball and Real Clear Politics.</p>
<p>With this data, the model predicts that Democrats will win 49.5% of the two party vote share and Republicans will win 50.5% of the two party vote share. Unfortunately, the prediction interval remains very large with the prediction falling between 44-55 points for Democrats.</p>
<p>I then used these predictions to predict seats won by each party based on a simple bivartiate model converting vote share to seat share.</p>
<p>#Seat Share Model</p>
<pre><code>## 
## ===============================================
##                         Dependent variable:    
##                     ---------------------------
##                               d_seats          
## -----------------------------------------------
## D_majorvote_pct              8.790***          
##                               (0.766)          
##                                                
## Constant                    -219.768***        
##                              (40.047)          
##                                                
## -----------------------------------------------
## Observations                    30             
## R2                             0.825           
## Adjusted R2                    0.819           
## Residual Std. Error      13.516 (df = 28)      
## F Statistic           131.831*** (df = 1; 28)  
## ===============================================
## Note:               *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
<p>Ideally, I would predict seat share directly as the dependent variable however, since we are limited to only three years of seat share data, it was impossible to build a robust model in this way. However, to work around this I ran a simple bivariate regression on Democratic two party vote share and Democratic seats share since 1948. The r2 on this model was .825 suggesting a very strong relationship. While this does introduce added uncertainty since I am predicting based on a prediction, it was the most reasonable way to use the model to get a seat share prediction.</p>
<pre><code>##        fit      lwr      upr
## 1 208.5605 179.8909 237.2301</code></pre>
<p>Based on the predicted vote share, I predict that Democrats will win 209 House seats and Republicans will win 226. This prediction has a large uncertainty interval with a low of 179 seats and a high of 237 seats.</p>
<p>#Assesing The Model</p>
<p>While the model is based on observations at the district-year level, the data I input for the prediction is based on an aggregate of the current national environment and expert predictions. To check how this holds up to the model, I aggregated all data points for each of the 3 years included in the data set and graphed them against the model.</p>
<p><img src="/post/2022-11-05-final-election-forecast/Test_pdf_files/figure-html/unnamed-chunk-17-1.png" width="672" />
As we can see, the year aggregates are good fits for the model which validates the approach used to make the prediction.</p>
<p>In-sample validation
<img src="/post/2022-11-05-final-election-forecast/Test_pdf_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<pre><code>## [1] 2.690822</code></pre>
<p>If we look at the the distribution of residuals we see that there appears to be a slight leftward skew but they are for the most part normal. This further supports the validity of the model as we expect a normal distribution of residuals with linear models. Furthermore, the mean squared error is 2.69 which is much lower than the MSE in the alternative model which included all election years (~12). This validates the choice of the midterm years model over the model including all election years.</p>
<p>Out-of-sample validation</p>
<pre><code>## [1] -2.99101</code></pre>
<p>When looking at out-of-sample validation, the model does not hold up particularly well to the removal of data from a given year resulting in a mean out of sample residual of -2.99. This is to be expected given that the model only incorporates three years worth of data. his means that an out of sample test removing one year removes about 1/3 of the observations. Therefore, I expect that this test is over inflating residuals as a lack of limited data. Since the unit of observation for the model is district-year, I have chose to also test the models robustness when removing certain states.</p>
<p><img src="/post/2022-11-05-final-election-forecast/Test_pdf_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<pre><code>## [1] 0.3639304</code></pre>
<p>This out-of-sample test shows low residuals with a mean out of sample error of 0.3484196. This indicates that the model holds up much better across states than across years. This makes a sense given that this test is not pulling 1/3 of the data the way the previous one was.</p>
<div id="nh-01-model" class="section level2">
<h2>NH-01 Model</h2>
<p>While I did not model every district at the district level, I did want to include a forecast for the district I have been following for the class throughout the semester. As with all of the district level predictions, the ability to predict NH-01 is limited by the availability of data. This rough model includes average expert rating and incumbency. With such limited data, the r-squared is extremely low (0.296) and the prediction interval is 9 points in either direction. While teh predictive power of this model is quite low, I nevertheless predict with a great deal of uncertainty that Chris Pappas will narrowly take NH-01, over challenger Karoline Leavitt winning a two party vote share of 50.24%.</p>
<pre><code>## 
## ===============================================
##                         Dependent variable:    
##                     ---------------------------
##                       dem_votes_major_percent  
## -----------------------------------------------
## avg_rating                    -1.277           
##                               (1.322)          
##                                                
## dem_status                    -1.506           
##                               (1.933)          
##                                                
## Constant                     56.618***         
##                               (4.603)          
##                                                
## -----------------------------------------------
## Observations                     6             
## R2                             0.296           
## Adjusted R2                   -0.173           
## Residual Std. Error       2.306 (df = 3)       
## F Statistic              0.631 (df = 2; 3)     
## ===============================================
## Note:               *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
<pre><code>##        fit      lwr      upr
## 1 50.24223 41.10589 59.37856</code></pre>
<p>Expert ratings data sets were provided courtesy of Jackson Delgado. All other data incorporated in this model was provided courtesy of the Gov_1347 teaching staff.</p>
<p>Andrew Healy and Gabriel S Lenz. Substituting the end for the whole: Why voters respond
primarily to the election-year economy. American journal of political science, 58(1):31–47,
2014. ISSN 0092-5853. URL.</p>
<p>James Campbell. Forecasting the 2018 us midterm elections. PS: Political Science &amp; Politics,
51(S1), 2018. URL.</p>
</div>


		
	</div>

	<div class="pagination">
		<a href="/post/2022-10-25-blog-7/" class="left arrow">&#8592;</a>

		<a href="#" class="top">Top</a>
	</div>
</main>


        		<footer>
			
			<span>
			&copy; <time datetime="2022-11-18 15:44:54.896528 -0500 EST m=&#43;0.313871071">2022</time> . Made with <a href='https://gohugo.io'>Hugo</a> using the <a href='https://github.com/EmielH/tale-hugo/'>Tale</a> theme.
			</span>
		</footer>

    </body>
</html>
